pipeline {

    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t flask-demo:v1 .'
                }
            }
        }

        stage('Verify Image') {
            steps {
                sh 'docker images | grep flask-demo'
            }
        }
    }
}
