pipeline {

    agent any

    tools {
        sonarQube 'sonar-scanner'
    }

    stages {

        stage('SonarQube Scan') {
            steps {
                dir('app') {
                    withSonarQubeEnv('sonarqube') {
                        sh 'sonar-scanner'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t flask-demo:v1 .'
                }
            }
        }

        stage('Verify Image') {
            steps {
                sh 'docker images | grep flask-demo'
            }
        }
    }
}
